version: "3"
services:
  backend:
    image: sraj21/spemajor-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/spemajor?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "9192:9192"
#    networks:
#      - debtly-network
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spemajor
    volumes:
      - ./db:/var/lib/mysql


  frontend:
    image: sraj21/spemajor-frontend
    stdin_open: true               # To prevent the container from exiting abruptly.
    ports:
      - "3000:3000"
    depends_on:
      - backend
#    networks:
#      - debtly-network

#networks:
#  debtly-network:

